version: '3.11'

services:
  web:
    build: ./
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application

    volumes:
      - ./:/usr/src/app/
      - /var/www/back/static/:/usr/src/app/static/
      - /var/www/back/media/:/usr/src/app/media/
    ports:
      - 8000:8000
    env_file:
      - ./.env.docker
    depends_on:
#      - db
      - redis

#  db:
#    image: postgres:14-alpine
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    environment:
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_DB=${POSTGRES_DB}

  redis:
    image: redis:latest
    ports:
      - 6379:6379

#volumes:
#  postgres_data:
